language: minimal

services: docker

env:
  global:
    - IMAGE_TAG=$TRAVIS_COMMIT

install:
  - TARGET=prod make build
  - TARGET=dev make build

script:
  - TARGET=prod .travis/smoke-test.sh
  - TARGET=dev .travis/smoke-test.sh
  - TARGET=prod .travis/analyse.sh
  - TARGET=dev .travis/analyse.sh
  - make lint
  - make test
