version: '3.4'

services:
  app:
    build:
      target: test
    image: libero/article-store:${IMAGE_TAG:-master}-dev
    volumes:
      - ../.eslintignore:/app/.eslintignore
      - ../.eslintrc.js:/app/.eslintrc.js
      - ../jest.config.js:/app/jest.config.js
      - ../src/:/app/src
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../test/:/app/test
      - ../tsconfig.json:/app/tsconfig.json
